// Generated by CoffeeScript 1.10.0

/**
*
* The DaButton
*
* @class DaButton
*
* @author C.J. Morrison
*
* @since 10/12/2016
*
 */

(function() {
  var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  window.DaButton = (function() {

    /**
    *
    * ID associated with object, this is used for searching and selecting, this is required and must be unique
    *
    * @property _id
    *
    * @type {String}
    *
    * @default void 0
    *
     */
    DaButton.prototype._id = void 0;


    /**
    *
    * Drawing Area Reference, this will reference the Drawing Area this Button is associated with.
    *
    * @property _daRef
    *
    * @type {DrawingArea}
    *
    * @default void 0
    *
     */

    DaButton.prototype._daRef = void 0;


    /**
    *
    * Drawing Area Manager Reference, this will reference the Drawing Area Manager that the Drawing area that contains this button is associated with.
    *
    * @property _daManagerRef
    *
    * @type {DrawingAreaManager}
    *
    * @default void 0
    *
     */

    DaButton.prototype._daManagerRef = void 0;


    /**
    *
    * An array of options with their values
    *
    * @property _options
    *
    * @type {Array}
    *
    * @default void 0
    *
     */

    DaButton.prototype._options = void 0;


    /**
    *
    * The width of this button
    *
    * @property _width
    *
    * @type {Number}
    *
    * @default 0
    *
     */

    DaButton.prototype._width = void 0;


    /**
    *
    * The height of this button
    *
    * @property _height
    *
    * @type {Number}
    *
    * @default 0
    *
     */

    DaButton.prototype._height = void 0;


    /**
    *
    * Is the button currently enabled, if false the button will not accept mouse input. 
    *
    * @property _enabled
    *
    * @type {Boolean}
    *
    * @default 0
    *
     */

    DaButton.prototype._enabled = void 0;


    /**
    *
    * Is the button currently hidden, if false the button will not accept mouse input. 
    *
    * @property _hidden
    *
    * @type {Boolean}
    *
    * @default 0
    *
     */

    DaButton.prototype._hidden = void 0;


    /**
    *
    * The container for the button shapes icons and text of all states
    *
    * @property _container
    *
    * @type {createJS._container}
    *
    * @default 0
    *
     */

    DaButton.prototype._container = void 0;


    /**
    *
    * The container for the button shapes icons and text of only the normal state
    *
    * @property _normalState
    *
    * @type {createJS._container}
    *
    * @default 0
    *
     */

    DaButton.prototype._normalState = void 0;


    /**
    *
    * The container for the button shapes icons and text of only the over state
    *
    * @property _overState
    *
    * @type {createJS._container}
    *
    * @default 0
    *
     */

    DaButton.prototype._overState = void 0;


    /**
    *
    * Constructor will define the properties for this class and call Build method
    *
    * @method DaButton
    * 
    * @param daRef - Drawing Area Reference.
    * @param options - array of options and values for this button (includes id)
    * @return void 0
    *
     */

    function DaButton(daRef, options) {
      this.Show = bind(this.Show, this);
      this.Hide = bind(this.Hide, this);
      this.Disable = bind(this.Disable, this);
      this.Enable = bind(this.Enable, this);
      this.HandleClick = bind(this.HandleClick, this);
      this.HandleMouseOut = bind(this.HandleMouseOut, this);
      this.HandleMouseOver = bind(this.HandleMouseOver, this);
      this.Move = bind(this.Move, this);
      this.BuildState = bind(this.BuildState, this);
      this.Build = bind(this.Build, this);
      this._daRef = daRef;
      this._daManagerRef = daRef._managerRef;
      this._options = options;
      this._id = options.id;
      this._enabled = true;
      this._width = 0;
      this._height = 0;
      this.Build();
    }


    /**
    *
    * @method Build
    *
    * Defines the buttons container and mouse events.
    *
    * @param Void 0
    * @return this
    *
     */

    DaButton.prototype.Build = function() {
      if (this._options.frameLoc === void 0) {
        this._options.frameLoc = [0, 0, 0];
      }
      this._container = new createjs.Container();
      this.BuildState('normal');
      this.BuildState('over');
      this.BuildState('disabled');
      this._container.addEventListener('mouseover', this.HandleMouseOver);
      this._container.addEventListener('mouseout', this.HandleMouseOut);
      this._container.addEventListener('click', this.HandleClick);
      this._overState.visible = false;
      this._disabledState.visible = false;
      this._container.addChild(this._normalState);
      this._container.addChild(this._overState);
      this._container.addChild(this._disabledState);
      if (this._options.xPos) {
        this._container.x = this._options.xPos;
      }
      if (this._options.yPos) {
        this._container.y = this._options.yPos;
      }
      return this;
    };


    /**
    *
    * @method BuildState
    *
    * Defines the sub containers for each state of the button ("normal", "over")
    * This includes shapes, labels, and icons.
    *
    * @param state:String - that state to be built
    * @return Void 0
    *
     */

    DaButton.prototype.BuildState = function(state) {
      var bitmap, buttonBG, color, fillColor, font, frmDat, height, i, icon, imgRes, label, len, obj, padding, radius, ref, size, togSheet, useText, width;
      this["_" + state + "State"] = new createjs.Container();
      if (this._options.useBackground) {
        if (this._options.useBackground.constructor === String) {
          bitmap = new createjs.Bitmap(this._options.useBackground);
          toolbarBGcont.addChild(bitmap);
          this._width = bitmap.width;
          this._height = bitmap.height;
        } else if (this._options.useBackground.constructor === Object) {
          this._options.useBackground = [this._options.useBackground];
        }
        if (this._options.useBackground.constructor === Array) {
          ref = this._options.useBackground;
          for (i = 0, len = ref.length; i < len; i++) {
            obj = ref[i];
            if (obj[state + "FillColor"]) {
              fillColor = obj[state + "FillColor"];
            } else {
              fillColor = "RGB(200, 200, 200)";
            }
            if (obj.width) {
              width = obj.width;
            } else {
              width = 50;
            }
            this._width = Math.max(this._width, width);
            if (obj.height) {
              height = obj.height;
            } else {
              height = this._daRef._cjsStage.canvas.height;
            }
            this._height = Math.max(this._height, height);
            if (obj.radius) {
              if (obj.radius.constructor === Number) {
                radius = [obj.radius, obj.radius, obj.radius, obj.radius];
              } else if (obj.radius.constructor === Array) {
                if (obj.radius.length === 2) {
                  radius = [obj.radius[0], obj.radius[0], obj.radius[1], obj.radius[1]];
                } else if (obj.radius.length === 4) {
                  radius = obj.radius;
                }
              }
            } else {
              radius = [0, 0, 0, 0];
            }
            buttonBG = new createjs.Shape;
            buttonBG.graphics.beginFill(fillColor);
            if (obj[state + "StrokeColor"] || obj[state + "StrokeWidth"]) {
              if (obj[state + "StrokeWidth"]) {
                buttonBG.graphics.setStrokeStyle(obj[state + "StrokeWidth"], "round");
              } else {
                buttonBG.graphics.setStrokeStyle(1, "round");
              }
              buttonBG.graphics.beginStroke(obj[state + "StrokeColor"]);
            }
            buttonBG.graphics.drawRoundRectComplex(0, 0, width, height, radius[0], radius[1], radius[2], radius[3]);
            this["_" + state + "State"].addChild(buttonBG);
          }
        }
      }
      if (this._options.useIcon !== void 0) {
        if (!this._options.useIcon[state + "FrameLoc"] && this._options.useIcon.frameLoc !== void 0) {
          this._options.useIcon[state + "FrameLoc"] = this._options.useIcon.frameLoc;
        }
        if (this._options.useIcon[state + "FrameLoc"] !== void 0) {
          imgRes = this._daManagerRef._loadedAssets.getResult(this._options.useIcon.resource);
          frmDat = JSON.parse(imgRes.dataset.frameData);
          if (this._options.useIcon[state + "FrameLoc"].constructor === Number) {
            this._options.useIcon[state + "FrameLoc"] = [this._options.useIcon[state + "FrameLoc"], this._options.useIcon[state + "FrameLoc"]];
          }
          togSheet = new createjs.SpriteSheet({
            "images": [imgRes],
            "frames": frmDat,
            "animations": {
              "norm": [this._options.useIcon[state + "FrameLoc"][0]],
              "over": [this._options.useIcon[state + "FrameLoc"][1]]
            }
          });
          icon = new createjs.Sprite(togSheet, "norm");
          icon.width = frmDat[this._options.useIcon[state + "FrameLoc"][0]][2];
          icon.height = frmDat[this._options.useIcon[state + "FrameLoc"][0]][3];
        } else {
          icon = new createjs.Bitmap(this._options.useIcon.resource);
          icon.width = icon.image.width;
          icon.height = icon.image.height;
        }
        if (this._options.useIcon.position === "left") {
          icon.x = 8;
          icon.y = (this._height - icon.height) / 2;
        } else if (this._options.useIcon.position === "right") {
          icon.x = this._width - icon.width - 8;
          icon.y = (this._height - icon.height) / 2;
        }
        this["_" + state + "State"].addChild(icon);
      }
      if (this._options.label) {
        if (!this._options.labelOptions) {
          this._options.labelOptions = {};
        }
        if (this._options.labelOptions.color) {
          color = this._options.labelOptions.color;
        } else {
          color = "#000";
        }
        if (this._options.labelOptions.size) {
          size = this._options.labelOptions.size;
        } else {
          size = "" + (20 * this._daManagerRef._fontScaleAdjust);
        }
        if (this._options.labelOptions.font) {
          font = this._options.labelOptions.font;
        } else {
          font = this._daManagerRef._defaultFont;
        }
        if (this._options.labelOptions.padding) {
          padding = parseInt(this._options.labelOptions.padding);
        } else {
          padding = 0;
        }
        if (!obj[state + "AltText"]) {
          useText = this._options.label;
        } else {
          useText = obj[state + "AltText"];
        }
        label = new createjs.Text(useText, "bold " + size + "px " + font, color);
        if (!this._options.useIcon) {
          label.textAlign = "center";
          label.y = 2 + padding;
          label.x = obj.width / 2 + padding;
        } else if (this._options.useIcon.position === "left") {
          label.textAlign = "left";
          label.y = 2 + padding;
          label.x = icon.width + icon.x + 7 + padding;
        } else {
          label.textAlign = "left";
          label.y = 2 + padding;
          label.x = 7 + padding;
        }
        if (this._daManagerRef._FFtextAdjust) {
          label.y += 3;
        }
        this["_" + state + "State"].addChild(label);
      }
    };


    /**
    *
    * @method Move
    *
    * Moves Button to desired X and Y coordinates
    *
    * @param x:Number the X position the button will be moved to
    * @param y:Number the Y position the button will be moved to
    * @return Void 0
    *
     */

    DaButton.prototype.Move = function(x, y) {
      this._container.x = x;
      this._container.y = y;
    };


    /**
    *
    * @method HandleMouseOver
    *
    * Event function called when mouse is over the button. this will change the state to over
    *
    * @param e:Event Mouse event
    * @return Void 0
    *
     */

    DaButton.prototype.HandleMouseOver = function(e) {
      if (this._enabled && !this._hidden) {
        this._overState.visible = true;
      }
    };


    /**
    *
    * @method HandleMouseOut
    *
    * Event function called when mouse leaves the button. this will change the state to normal
    *
    * @param e:Event Mouse event
    * @return Void 0
    *
     */

    DaButton.prototype.HandleMouseOut = function(e) {
      if (this._enabled) {
        this._overState.visible = false;
      }
    };


    /**
    *
    * @method HandleClick
    *
    * Event function called when mouse has clicked while over the button. this will change the state to normal and activate whichever function is associated with the button.
    *
    * @param e:Event Mouse event
    * @return Void 0
    *
     */

    DaButton.prototype.HandleClick = function(e) {
      var aa, cPrm, i, len, newParam, prm, ref, useParams;
      if (this._enabled && !this._hidden) {
        createjs.Sound.play("def_select");
        this._overState.visible = false;
        if (!this._options.onActivateParams || this._options.onActivateParams.constructor !== Array) {
          useParams = [
            {
              data: this._options.onActivateParams,
              caller: this
            }
          ];
        } else {
          newParam = [];
          ref = this._options.onActivateParams;
          for (i = 0, len = ref.length; i < len; i++) {
            prm = ref[i];
            cPrm = prm.valueOf();
            if (cPrm.constructor !== Object) {
              cPrm = {
                data: cPrm
              };
            }
            cPrm.caller = this;
            newParam.push(cPrm);
          }
          useParams = newParam;
        }
        if (this._options.onActivate) {
          if (this._options.onActivate.constructor === String) {
            this._daManagerRef.CustomEventCall(this._options.onActivate, this._daRef, useParams);
          } else if (this._options.onActivate.constructor === Array) {
            aa = 0;
            while (aa < this._options.onActivate.length) {
              this._daManagerRef.CustomEventCall(this._options.onActivate[aa], this._daRef, useParams[aa]);
              aa++;
            }
          }
        }
        this._daRef.HandleInternalEvent("onButtonClick", {
          target: this
        });
      }
    };


    /**
    *
    * @method Enable
    *
    * Enables the button
    *
    * @param Void 0
    * @return Void 0
    *
     */

    DaButton.prototype.Enable = function() {
      this._enabled = true;
      if (!this._hidden) {
        this._disabledState.visible = false;
        this._normalState.visible = true;
        this._daRef._cjsStage.update();
      }
    };


    /**
    *
    * @method Disable
    *
    * Disables the button
    *
    * @param Void 0
    * @return Void 0
    *
     */

    DaButton.prototype.Disable = function() {
      this._enabled = false;
      if (!this._hidden) {
        this._disabledState.visible = true;
        this._daRef._cjsStage.update();
      }
    };


    /**
    *
    * @method Hide
    *
    * Hides the button
    *
    * @param Void 0
    * @return Void 0
    *
     */

    DaButton.prototype.Hide = function() {
      this._hidden = true;
      this._normalState.visible = false;
      this._overState.visible = false;
      this._disabledState.visible = false;
    };


    /**
    *
    * @method Show
    *
    * Shows the button
    *
    * @param Void 0
    * @return Void 0
    *
     */

    DaButton.prototype.Show = function() {
      this._hidden = false;
      if (this._enabled) {
        this._normalState.visible = true;
      } else {
        this._disabledState.visible = true;
      }
    };

    return DaButton;

  })();

}).call(this);
